[theme]
base = "light"
primaryColor = "#9FB3DF"             
backgroundColor = "#F1F0E8"          
secondaryBackgroundColor = "#E5E1DA" 
textColor = "#474a51"                
linkColor = "#B3C8CF"                



