[theme]
base = "light"
primaryColor = "#89A8B2"             # Приглушенный сине-зеленый для основного акцента
backgroundColor = "#F1F0E8"          # Очень светлый, почти бумажный фон, напоминающий тетрадный лист
secondaryBackgroundColor = "#E5E1DA" # Теплый светло-бежевый для фона интерактивных элементов
textColor = "#333333"                # Стандартный темный цвет для читаемого текста
linkColor = "#B3C8CF"                # Светлый прохладный оттенок для выделения ссылок
